### ISSUE TITLE
Peer Review Draft analysis Gruppe C

### ISSUE THREAD

**Issue by NadineBraun** [Data-Analytics-WS2324-DM-DR/data-analytics-project#7]
**Peer review team**

- Peer review by: Gruppe C
- Names of team members that participated in this review: Nadine Braun, Alena Vetter

**Goal of the project**

Ziel ist es, Einflussgrößen auf das Wachstum von Dalmatinisches Leinkraut zu bestimmen. Hierfür soll die Größe des Krauts anhand bestimmter Faktoren vorhergesagt werden. 
Außerdem soll analysiert werden, ob das Wachstum des Leinkrauts durch eine Rüsselkäferpopulation eingedämmt werden
kann.

**Data**

- Das Dataset enthält insgesamt 25 Spalten und 1066 Zeilen. 
- Es enthält verschiedene Pflanzen mit Informationen zur Größe des Leinkrauts in der genommenen Probe sowie zur Rüsselkäferpopulation in eben dieser. 
- Die Daten wurden von Lincoln Smith an sechs verschiedenen Standorten erhoben.
- Da die Daten im Dataset die notwendigen Informationen zur Beantwortung der Fragestellungen enthalten, eignen sie sich zur Durchführung der angedachten Analysen.

**Approach, tools and methods**

_Lineare Regression:_ 
- Mithilfe einer linearen Regression wird die Hauptstammlänge des Leinkrauts in Abhängigkeit der Variablen stem_diam_bottom_in_cm, total_meja, meja_per_100_cm, diam_top_in_cm, side_branches_in_cm ermittelt. 
- Hierfür werden die Daten zunächst von NaN-Werten bereinigt. Hierbei werden drei verschiedene Methoden genutzt, die Nan-Werte werden entweder eliminiert, oder durch den Median oder Durchschnittswert ersetzt. 
- Danach werden sie in Trainigs- und Testdaten gesplittet. 
- Anschließend wird ein Überblick über die Daten sowie ihre Beziehung untereinander gegeben, zum einen in tabellarischer Form wie auch mithilfe von Diagrammen.
- Danach wird das lineare Regressionsmodell gefittet und mithilfe von MSE, RMSE, MAE und R^2 bewertet.

_Logistische Regression:_ 
- Mithilfe der logistischen Regression soll bestimmt werden, ob eine Pflanze mit Rüsselkäfern befallen ist oder nicht, um so eine Aussage darüber treffen zu können, ob diese als natürliches Bekämpfungsmittel nützlich sind oder nicht. 
- Dies geschieht anhand folgender Parameter: main_stem_length_cm, stem_diam_bottom_cm, side_branches_cm, diam_top_cm, tip_of_stem_broken, site, total_meja, meja_per_100_cm, total_number_adults. 
- Hierfür werden die Daten zunächst von NaN-Werten bereinigt. Hierbei werden drei verschiedene Methoden genutzt, die Nan-Werte werden entweder eliminiert, oder durch den Median oder Durchschnittswert ersetzt. 
- Danach werden sie in Trainigs- und Testdaten gesplittet. 
- Anschließend wird ein Überblick über die Daten sowie ihre Beziehung untereinander gegeben, zum einen in tabellarischer Form wie auch mithilfe von Diagrammen. 
- Danach wird das logistische Regressionsmodell gefittet und mithilfe von Confusion Matrix, Classification Report, sowie ROC und AOC bewertet.

**Lack of clarity**

- Aus dem Draft ist nicht unmittelbar ersichtlich, von wo die Daten kommen und was genau ein einzelner Datensatz repräsentiert. Hier wäre eine Ergänzung der Informationen aus dem Project Proposal sinnvoll.
- Die Beschreibungen im Data Dictionary ist für uns als Außenstehende nicht immer ganz verständlich. Das Problem könnte in der Realität allerdings weniger eine Rolle spielen, da man es hier überwiegend mit fachkundigen Personen zu tun hat.

**Possible improvements**

- Eventuell könnten die Ergebnisse der Modelle mithilfe von Anpassungen, wie z.B. Eliminierung von Ausreißern und Reduzierung der Inputvariablen verbessert werden. 
- Auch eine Anwendung von Forward Selection und Backwards Feature Elimination sinnvoll sein, um das Modell auf die wirklich relevanten Variablen zu beschränken.

**Presentation**

- Wie seid ihr auf das Thema gekommen?
- Was war die größte Herausforderung beim Modellieren?
- Wie stark haben sich die Ergebnisse unterschieden, als ihr die NaN-Werte unterschiedlich behandelt habt (Option 1 und 2)?

**Organization**

- Bei der Kommentierung in den Codes wäre es schön, einheitlich zu bleiben, dass also entweder immer Kommentierungen für das bessere Verständnis enthalten sind, oder die ganze Kommentierung im Fließtext erfolgt. 
- Ansonsten ist der Aufbau des Projekts sehr strukturiert und nachvollziehbar aufgebaut.

**Further comments**

Eine andere Möglichkeit der Aufteilung wäre, zuerst die vollständige lineare Regression und dann die
vollständige logistische Regression durchzuführen, anstatt die einzelnen Schritte jeweils immer für
beide Modelle zu machen. Das könnte den Lesefluss verbessern, ist aber vermutliche persönlicher
Geschmack.

**Comment by DavidRmn** [comment]
Thank you for the Feedback!
