### ISSUE TITLE
Peer Review - Gruppe F

### ISSUE THREAD

**Issue by felixdaubner** [Data-Analytics-WS2324-DM-DR/data-analytics-project#8]
### Peer review team

- Peer review by: Gruppe F
- Names of team members that participated in this review: Jenny Schönfeld, Jimi Kim, Felix Daubner

### Goal of the project
Ziel des Projekts ist es, mit Hilfe von Daten die Ausbreitung von Unkraut ("Dalmatian toadflax") durch die gezielte Freisetzung von Käfern einzudämmen. Die Daten werden zur Vorhersage der Pflanzengröße (Regression) und zur Feststellung, ob die Pflanze von einem Befall betroffen ist (Klassifikation), verwendet, um die Wirksamkeit dieser Unkrautbekämpfungsmethode zu ermitteln.

### Data
Die Daten wurden vom Agricultural Research Service für verschiedene Gebiete und Jahre veröffentlicht. Jede Beobachtung steht für eine Pflanze in dem untersuchten Gebiet. Der Datensatz enthält 1066 Zeilen (Beobachtungen) mit jeweils 25 Spalten (Features). Etwa die Hälfte der Spalten enthalten alle Werte und sind somit vollständig. Einige Spalten enthalten sogar gar keine Werte. 

Wenn man sich das "data dictionary" ansieht, scheinen die Daten für das Projekt geeignet zu sein, da sie zahlreiche Informationen über das Unkraut enthalten, wie z. B. den Durchmesser des Stängels am Boden oder die kumulative Länge der Seitenäste. All diese Informationen scheinen für die zu treffenden Vorhersagen nützlich zu sein.

### Approach, tools and methods
Bis einschließlich Kapitel 3.4 wird zunächst der Datensatz vorgestellt, Spaltennamen angepasst und bestimmte Spalten auf ein anderes Format / Einheit konvertiert. 
Anschließend werden die fehlenden Werte auf eine von drei verschiedene Arten (Ersetzen durch Median, Ersetzen durch Mean, Löschen) ersetzt / eliminiert. Dabei ist anzumerken, dass beim Anwenden einer Methode alle Daten durch dieses Vorgehen ersetzt / eliminiert werden. D.h. eine "Misch"-Anwendung verschiedener Methoden wird nicht umgesetzt.
Basierend auf den Variablenlisten aus Kapitel 3.4 werden schließlich die Daten gesplittet, sodass die EDA durchgeführt werden kann.
Durch das Anwenden der Cross Validation wird die Konsistenz der Daten beurteilt. Bei der linearen Regression geschieht dies anhand des "Mean Squared Errors", bei der logistischen Regression mittels der "Accuracy".
Anschließend werden die Modelle mit den Trainingsdaten trainiert und die Modell mit den gängigen Metriken evaluiert. 

Die verwendeten Bibliotheken sind pandas, altair, sklearn und pickle. 

### Lack of clarity
- Feature selection: Basierend auf welchen Metriken / Charakteristika wurden die "predictor"-Variablen ausgewählt? In Kapitel 3.4 wurden für Regression und Klassifikation jeweils die Variablenlisten angegeben, ohne eine Erläuterung / Begründung, wieso speziell diese Variablen für das Modell sinnvoll sind.
- Forward Selection: In der "draft-analysis" wird mehrfach die "forward selection" erwähnt, mit der die "predictor"-Variablen ausgewählt werden. Der Prozess bzw. die Durchführung der "forward selection" fehlt jedoch im Notebook. 
- Multicollinearity: Auf Multikollinearität wird kurz eingegangen und hingewiesen, dass dies vermieden werden soll. Gleichzeitig wird gesagt, dass "predictor"-Variablen mit hoher Korrelation aus dem Modell entfernt werden. Welche Variablen das sind, wird nicht erwähnt.

### Possible improvements
- Literature: Leider findet sich keine Literatur in der Einleitung, worauf die Forschungsfrage(n) oder die Hypothesen aufbauen.
- Descriptive statistics: Hierbei hätte kurz auf die Daten und evtl. auftretende Besonderheiten eingegangen werden können. 
- Outliers / Influential points: Bereits in der deskriptiven Statistik lassen sich Ausreißer erkennen. Gerade für die Lineare Regression hätten mithilfe der IQR oder dem z-score Ausreißer bzw. "Influential points" identifiziert und ggf. entfernt werden können, um die Modellgüte zu optimieren.
- Decision thresholds: Bei der logistischen Regression hätte mithilfe der "decision thresholds" evaluiert werden können, ob das Modell bei anderen Grenzen besser / schlechter performt. 

### Presentation
- Das Vorgehen im Kapitel "Data Splitting and Imputation" ist sehr interessant. Bestenfalls könnt ihr darauf eingehen und kurz beschreiben, warum ihr so vorgegangen seid. Eine Frage hierbei wäre, wieso ihr nicht für jede Variable einzeln entschieden habt, ob der Durchschnitt oder Median verwendet wird, sondern immer nur im Kollektiv?
- Bei der Evaluation der Klassifikation könntet ihr kurz darauf eingehen, ob euer Modell eher auf Precision oder Recall optimiert werden soll.

### Organization
Der Code und das Repo sind übersichtlich und nachvollziehbar strukturiert. An manchen Stellen ist die Ausführung jedoch etwas knapp oder fehlt.

**Comment by DavidRmn** [comment]
Thank you for the Feedback!
